name: design
description: Design system
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  diff_match_patch: ^0.4.1
  flutter_highlight: ^0.7.0
  web: ^0.5.1
  sliver_tools: ^0.2.12
  flutter_staggered_grid_view: ^0.7.0
  logger: ^2.1.0
  linked_scroll_controller: ^0.2.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
    - family: Meslo
      fonts:
        - asset: assets/fonts/Meslo LG v1.2/MesloLGS-Regular.ttf
          weight: 400
        - asset: assets/fonts/Meslo LG v1.2/MesloLGM-Regular.ttf
          weight: 500
        - asset: assets/fonts/Meslo LG v1.2/MesloLGL-Regular.ttf
          weight: 600
        - asset: assets/fonts/Meslo LG v1.2/MesloLGS-Bold.ttf
          weight: 700
        - asset: assets/fonts/Meslo LG v1.2/MesloLGM-Bold.ttf
          weight: 800
        - asset: assets/fonts/Meslo LG v1.2/MesloLGL-Bold.ttf
          weight: 900