name: source_demo
description: ""
version: 0.0.0
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  design:
    path: ../system
  cupertino_icons: ^1.0.6
  creator: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

